# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Name the Job
    name: Unit Tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'

    # Runs Linters
    - name: Install Node dependencies
      if: always()
      run: yarn
    - name: Run client tests
      if: always()
      run: yarn test
    - name: Notify on failure
      if: failure()
      run: echo 'run "yarn test" to see/fix errors locally'
